const APIV1 = '/api/v1'
const APIV2 = '/api/v2'

module.exports = {
  name: '杭州目博',
  prefix: 'antdAdmin',
  footerText: '杭州目博科技有限公司 2017 版权所有 浙ICP备14013809号-1 电话:0571-83031258 浙江省杭州市',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: [],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: `${APIV1}/user/login`,
    userLogout: `${APIV1}/user/logout`,
    userInfo: `${APIV1}/userInfo`,
    users: `${APIV1}/users`,
    chargeStandards: `${APIV1}/chargeStandards`,
    parks: `${APIV1}/parks`,
    parkStalls: `${APIV1}/parkStalls`,
    baseStations: `${APIV1}/baseStations`,
    sensors: `${APIV1}/sensors`,
    inducedScreens: `${APIV1}/inducedScreens`,
    deviceDefends: `${APIV1}/deviceDefends`,
    parkingRecords: `${APIV1}/parkingRecords`,
    chargeRecords: `${APIV1}/chargeRecords`,
    infoPublishs: `${APIV1}/infoPublishs`,
    posts: `${APIV1}/posts`,
    user: `${APIV1}/user/:id`,
    chargeStandard: `${APIV1}/chargeStandard/:id`,
    park: `${APIV1}/park/:id`,
    parkStall: `${APIV1}/parkStall/:id`,
    baseStation: `${APIV1}/baseStation/:id`,
    sensor: `${APIV1}/sensor/:id`,
    inducedScreen: `${APIV1}/inducedScreen/:id`,
    deviceDefend: `${APIV1}/deviceDefend/:id`,
    parkingRecord: `${APIV1}/parkingRecord/:id`,
    chargeRecord: `${APIV1}/chargeRecord/:id`,
    infoPublish: `${APIV1}/infoPublish/:id`,
    dashboard: `${APIV1}/dashboard`,
    menus: `${APIV1}/menus`,
    v1test: `${APIV1}/test`,
    v2test: `${APIV2}/test`,
  },
}
